import mongoose from 'mongoose';

const PatientRecordSchema = new mongoose.Schema({
  basicInfo: {
    researchCaseNo: { type: String, trim: true },
    opdNo: { type: String, trim: true },
    name: { type: String, required: true, trim: true },
    ipdNo: { type: String, trim: true },
    fatherHusbandName: { type: String, trim: true },
    bedNo: { type: String, trim: true },
    age: { type: Number, required: true },
    sex: { type: String, required: true },
    religion: { type: String, trim: true },
    maritalStatus: String,
    occupation: { type: String, trim: true },
    socioEconomicStatus: { type: String, trim: true },
    education: { type: String, trim: true },
    address: { type: String, trim: true },
    phoneNo: { type: String, trim: true },
    investigatorName: { type: String, trim: true },
    patientConsent: { type: Boolean, default: false },
  },
  history: {
    chiefComplaints: { type: String, trim: true },
    presentIllness: {
      onset: { type: String, trim: true },
      duration: { type: String, trim: true },
      aggravationAt: { type: String, trim: true },
      degradationAt: { type: String, trim: true }
    },
    treatmentHistory: { type: String, trim: true },
    pastMedications: { type: String, trim: true },
    recentMedications: { type: String, trim: true },
    surgicalHistory: { type: String, trim: true },
  },
  personalHistory: {
    diet: String,
    dominantRasa: String,
    dietHabit: String,
    foodQuantity: String,
    birthPlace: String,
    presentHabitat: String,
    occupationNature: String,
    agni: String,
    kostha: String,
    appetite: String,
    bowelHabit: String,
    bladderHabit: String,
    sleep: String,
    sleepQuality: String,
    daytimeSleepDuration: String,
    previousNightSleep: String,
    exercise: String,
    addiction: [String],
    sharira: String,
    menstrualHistory: {
      menarcheAge: Number,
      menopauseAge: Number,
      flowDuration: String,
      flowNature: String,
      cycleDuration: Number,
      associatedSymptoms: String
    },
    ongoingMedications: String,
    familyHistory: String,
  },
  physicalExamination: {
    generalAppearance: String,
    built: String,
    weight: Number,
    height: Number,
    pallor: String,
    icterus: String,
    cyanosis: String,
    clubbing: String,
    lymphadenopathy: String,
    oedema: String,
    oedemaType: String,
    oedemaLocation: String,
    thyroidGland: String,
    vitals: {
      bp: String,
      pulseRate: String,
      respiratoryRate: String,
      temp: String,
    }
  },
  dashavidhaParikshana: {
    prakritiSharirik: String,
    prakritiMansika: String,
    vikritiDosha: String,
    saara: String,
    samahanana: String,
    pramana: String,
    satva: String,
    satmya: String,
    abhyavaharanaShakti: String,
    jaranaShakti: String,
    vyayamaShakti: String,
  },
  ashtavidhaPariksha: {
    nadi: String,
    mala: { matra: String, varna: String, gandha: String, pravritti: String, prakriti: String },
    jihwa: String,
    shabda: String,
    sparsha: String,
    drika: String,
    akriti: String,
    mutra: { matra: String, gandha: String, varna: String, pravritt: String }
  },
  jivhaPariksha: {
    color: String,
    coating: String,
    coatingTypeColor: String,
    odor: String,
    shape: String,
    moisture: String,
    texture: String,
    movement: String,
    associatedSymptoms: String,
    imageUrl: String
  },
  diagnosis: { type: String, trim: true },
  diagnosisImageUrl: String,
}, { timestamps: true });

export default mongoose.models.PatientRecord || mongoose.model('PatientRecord', PatientRecordSchema);